CONFIG_LOG=y
CONFIG_THREAD_NAME=y

CONFIG_LOG_BACKEND_UART=y
CONFIG_UART_CONSOLE=y

# Allow Debug logs to be compiled in
CONFIG_LOG_MAX_LEVEL=4

# Default to Info level for most modules (silences kernel debug spam)
CONFIG_LOG_DEFAULT_LEVEL=3

# REMOVE OR CHANGE THIS: 
# CONFIG_LOG_OVERRIDE_LEVEL=4  <-- Delete this line or set to 3